Speedy pass
Patribots4738/Crescendo2024 pull request #282
Opened 2024-04-01 17:18 UTC by derp00monsta

speedy-pass is now speedy passing and it doesn't seem to be messing with shooting into the speaker, but that's only in sim.

2024-04-02 03:03 UTC, Hadizah454 reviewed
It looks good to me and the images are a nice touch. There seems to be a merge conflict in the piece control class but I'll resolve it myself so you don't need to worry about that.

2024-04-02 03:09 UTC, Hadizah454 approved these changes
Actually nvm @derp00monsta can you try to resolve the merge conflict yourself because idk why but my computer is freaking out on me right now sorry.

2024-04-09 01:29 UTC, GalexY727 commented
I feel that there is a better way to do this rather than adding alignmentcmds into piececontrol, because that turns piececontrol into a second-hand "robotcontainer" type of file. I think that there should be some sort of method that we can get from alignmentcmds and pass into piececontrol rather than sending the entire file into inheritance. 

That was a lot of words and if I didn't type that out quite right let me know and I'll try to reword it.

2024-04-09 14:19 UTC, derp00monsta commented
> I feel that there is a better way to do this rather than adding alignmentcmds into piececontrol, because that turns piececontrol into a second-hand "robotcontainer" type of file. I think that there should be some sort of method that we can get from alignmentcmds and pass into piececontrol rather than sending the entire file into inheritance.
> 
> That was a lot of words and if I didn't type that out quite right let me know and I'll try to reword it.

How do we use a method from alignmentcmds w/out importing the file into piececontrol? None of the classes imported into piececontrol on main seem to have alignmentcmds in them either.
I think I might understand I'm just not sure how to do what you are suggesting.

2024-04-10 04:33 UTC, GalexY727 commented
> > I feel that there is a better way to do this rather than adding alignmentcmds into piececontrol, because that turns piececontrol into a second-hand "robotcontainer" type of file. I think that there should be some sort of method that we can get from alignmentcmds and pass into piececontrol rather than sending the entire file into inheritance.
> > That was a lot of words and if I didn't type that out quite right let me know and I'll try to reword it.
> 
> How do we use a method from alignmentcmds w/out importing the file into piececontrol? None of the classes imported into piececontrol on main seem to have alignmentcmds in them either. I think I might understand I'm just not sure how to do what you are suggesting.

We are going from full inheritance to just partial. If all we need is one method from alignmentcmds, we can give that method to piececontrol whenever we call the command, so robotcontainer is in fuller control over the scope of piececontrol.

2024-04-10 06:38 UTC, GalexY727 commented
one thing i would like to mention with this pr is that it removed the feature of waiting for hdc to be rotated before shooting, and although it was reintroduced inside of [9f96b1e](https://github.com/Patribots4738/Crescendo2024/pull/282/commits/9f96b1e990f8c773f060ca3dd8969a060b644210) i worry that there may be other features that got overlooked somehow.

2024-04-10 06:39 UTC, GalexY727 commented on src/main/java/frc/robot/subsystems/Pivot.java
> +    @Log
this formatting is bugged in github but looks fine in the code

2024-04-10 06:40 UTC, GalexY727 commented on src/main/java/frc/robot/subsystems/Pivot.java
> +    }
this formatting is bugged in github but looks fine in the code

2024-04-10 20:52 UTC, PatribotsProgramming requested changes
A small formatting fix and it would be nice to be able to test the limits of the deadband to see what the biggest amount of change we are allowing before we send it an a full comp

2024-04-10 20:52 UTC, PatribotsProgramming commented on src/main/java/frc/robot/commands/managers/PieceControl.java
> +            new ActiveConditionalCommand(
This doesn't need to be active, it should just be a either

2024-04-12 23:29 UTC, PatribotsProgramming approved these changes
If there are complications with our passing at comp then we can revert this pr woohoo1!!

2024-04-12 23:30 UTC, merged